### ISSUE TITLE
Issue 33171: The Golang Ternary Schism

### ISSUE THREAD

**Issue by dash-** [dash-/go#1]
I have temporarily forked Golang/Go and created this issue because the Golang overlords have stopped playing nice and they can no longer be trusted to host this conversation.

Regarding [Go Issue #33171](https://github.com/golang/go/issues/33171), I propose again there is a third option: compromise.

In short, the Golang overlords are still refusing to find a compromise regarding the ternary operator. I summarize the situation in my own words below, but it's lengthy. Essentially I predict a fork, though I later admit it might not be a fork but something else. What I am trying to do is create a place where we can continue the conversation.

There's a much longer version of summary here: #2

Maybe I'll make it into a Youtube video, because it's too much text for ppl to read.

**Comment by dash-** [comment]
https://github.com/golang/go/issues/46430

@ALTree said:

> Nice blog post!
> 
> > I personally suspect Google employees filled out the last of the 107 thumbs up and stopped after passing the 105 thumbs down, but that suspicion is admittedly groundless. (I'm sure I could investigate, it is accessible information, but I'm too lazy and just don't really care.)
> 
> This seems unlikely... but if you ever find time to investigate the matter, please report back on golang-dev. I would personally love to hear more about this.
> 
> > The compromise I suggested was allowing the ternary operator to be enabled via configuration, even if it is off by default.
> 
> Go is a fairly opinionated language. Essentially every single proposal to significantly alter the language by making it "configurable" (thus introducing "language dialects") has been turned down. Since your post here doesn't add much to the discussion at #33171, I'm closing here as a dup of #33171.

**Comment by dash-** [comment]
Of course he closes this issue's mirror at golang#46430

That's why this issue was created first and that issue was a mirror of this issue.

**Comment by dash-** [comment]
@ianlancetaylor said:

> I'll just add that the way to change a proposal decision is to provide new information. I don't see any new information here. Continuing discussion without new information just takes time without making progress. We have to be able to make a decision and move on, without continuously discussing the same issues. Thanks, and thanks for taking the time to write this.

**Comment by dash-** [comment]
@ianlancetaylor @ALTree 

Thanks for reading and the reply. Sorry I'm so verbose. I assumed it was preferred, but perhaps not. If not, perhaps consider making Go less verbose by adding ternary conditional operators.

There's no more examples I need to give about where a ternary conditional is better than an if statement. Plenty of people made those examples already, and had someone else say "oh I prefer this really verbose and terrible code, so no ternary." Because this is all just opinions. There isn't a right or wrong there, and that's why I'm not arguing about that part.

My goal of the prior summary was not to provide new information, but rather to sum up the previous conversation for the new venue outside overlord control. I did add more detail to my previous points, added that the conversation is actually taking place elsewhere now because the Golang overlords have been misbehaving and cannot be trusted to host the conversation, and added a prediction about the name of the fork. Although I don't have a lot of faith in that name prediction. Those kinds of predictions are really tough.

That having been said, I did introduce some new thoughts around this issue's relation to human suffering. It's not the kind of information you're looking for, but that's my point. You're not seeing it because you're in the wrong paradigm. I've been a developer for more than a couple decades, but it's my people experience as a lead, principal, and director that I'm speaking from. This conversation is about people, and is not so much about computer science. Otherwise, you're putting computer science before people, and that's fundamentally wrong (both morally and strategically).

People in the general software development community are being subjected against their will to your terrible opinions. Subjected by their jobs and their conditions, their bosses and their teachers. It causes them undue stress, increasing their cortisol, shortening their lifespan. Some of them quit their jobs. Others are fired as a result. You should read **their** blog entries. I even suspect it may have played a factor in at least one suicide. I don't have stats here, but even a conservative estimate would reveal that Golang has negatively affected at least several thousand of its ~1.1M developers. You're doing that to them on purpose, and acting like they are just overreacting. I take it you're not utilitarians. If you can't empathize with them, you should seek therapy. It is dangerous to not feel empathy when you hear about other people experiencing pain, and it should disqualify you from making product decisions. Even product decisions for a programming language.

Your terrible opinions are terrible because they are not evidence-based, and so when half of the world randomly disagrees because there is no right or wrong, you've made it feel like sandpaper on the skin to use your product. You could have been agnostic about the ternary conditional operator like the other popular languages and just included it outright. Instead you're torturing human beings.

Occasionally one of them finds the complaint department, and so you've closed the complaint department -- because when you're torturing people, having a complaint department seems like a wasteful expense.  It's not, it's actually how you suppress the insurrection, and when you close the complaint department that's when the insurrection really heats up. Something is going to happen. This isn't my first rodeo here, and I'm speaking from experience, but I don't know for sure what is going to happen. I predicted a fork, but it doesn't have to be a fork.

Pain results in reaction, and frequently overreaction. There will be an effect of this. Your attempts to "win" or "quell" all the little nitpicking fights of the software world are admirable, but you don't understand all the sciences involved well enough to actually win the very very difficult game you're playing. You're just using computer science, and it's not the dominant science here. Social sciences dominate here.

Human emotion is incredibly powerful when synchronized, so it's easy to predict the energy will go somewhere. It's far harder to predict where it will go. It might not be a fork. It could be a movement, but probably not. It could be violence, but probably not. It could be legislation, but probably not. It could just cause a little annoyance until Golang becomes less popular as new, better, evidence-based languages pop up, but probably not. Maybe it will just result in a preprocessor. That actually seems equally likely as a fork. Maybe even more likely.

One of the ideas I keep circling around and not saying is it's not up to the Golang overlords. It's up to us, the Golang user community. Y'all acting otherwise is ignorance. Me saying this is not what makes it so. It being so is what makes it so. The Go overlords will comply with the community eventually, because the community is everything. What's more, the community has powers beyond the overlords' control. We can fork, but we can also do worse.

It is this last bit that is what this new conversation is about. I'm basically over discussing the ternary operator. I'm mostly trying to negotiate a compromise on behalf of the minority party, but part of that is also having the discussion about what we, as the minority party, will do if compromise cannot be made.

**Comment by dash-** [comment]
Maybe rather than a fork, it's a preprocessor. I like that. How about `goliath`, which preprocesses the files and builds a nice environment for Go, but had a ternary operator and a few other things either permanently enabled or enabled by default.

If we make a version that doesn't even require installation, and can effectively be used over the network, I think we could even get some usage inside Google.  What do y'all think?

@phrounz
@alanfo
@ianlancetaylor
@donaldnevermore
@docmerlin
@dankobgd
@Eraarc
@apmattil
@mvjq
@deejayres
@alialtun14
@ysweid
@DeanPDX
@mmiranda96
@LUC18fknU7P
@replicadse
@SamuelKupferschmid
@Lexkane
@anjiawei1991
@relief-melone

**Comment by dash-** [comment]
Oh yeah, I guess I never really mentioned why I ever came to the original issue. I was relatively new in a position working as a Director at a medium sized corporation at the time, and the CTO above me insisted we use Go for new backend work instead of .NET, which the CTO and I both hated. I had enjoyed my dalliances with Go so the order was unopposed by me. I pushed it onto my subordinates, who pushed it onto theirs, and we started to dev backend in Go rather than .NET. A significant improvement, I thought. "These fortunate devs under me who get to finally use a modern tech stack and not just go down the dead-end of .NET development," I thought, at the time. But then I got pushback after awhile about these kinds of issues, things like unnecessary verbosity, poor readability, etc, and was blown away. That's when I came here back in March, 2020. Eventually, we realized that it wasn't going to change on any reasonable timescale, and we eventually just started looking at different options.  The CTO left and then I got cancer and left.  Last I heard they were back on .NET. Fun story huh.

Oh, and we also pushed them to switch to Vue. They're still using Vue.

**Comment by DeanPDX** [comment]
I'm not sure why you @'d me. I do *sometimes* miss ternary operators, but less frequently than I used to think I would. I primarily find they are more useful in front-end work. For example, in Angular I do things like this in my templates semi-frequently for brevity (and because I'm being lazy and putting too much logic in my template, but who's counting?):

```html
<!-- If form is valid, attempt login. Else mark form as touched so validation will display. -->
<form (ngSubmit)="loginForm.valid ? login() : loginForm.form.markAllAsTouched()" #loginForm="ngForm">
```

... and I don't think readability is a concern there. For schlepping strings around, however? I think [this](https://play.golang.org/p/87OGGB1eeGM) works fine:

```go
func main() {
	worlds := 1
	fmt.Println("Hello", Cond(worlds > 1, "Worlds", "World"))
	worlds = 2
	fmt.Println("Hello", Cond(worlds > 1, "Worlds", "World"))
}

func Cond(cond bool, replacement string, orig string) string {
	if cond == true {
		return replacement
	}
	return orig
}
```

**But what if I want something OTHER than a string?** Generics will solve that. Also almost every example I saw had to do with string manipulation. In my case, string manipulation is 95% of my use case and I'll accept a slight increase in verbosity on the other 5% for the ease of use that golang buys me.

As a consultant working with many different technologies and their corresponding ecosystems, I have come to appreciate the go core team's aversion to adding new things to the language. There were times in my .NET career when just keeping up with the sheer amount of new language features was difficult, let alone libraries / frameworks. And with each language feature, lexing becomes more complicated which has potential compiler performance ramifications. Go is incredibly simple, and it's not an accident. There are more complicated languages out there if you want that them. I think you'll find that nearly everything is a tradeoff.

Even if a fork implemented ternary operators, I wouldn't bother with it. The collective amount of time it would save me is probably less than I just took to type this comment, and I don't really miss them that badly. I think this is very sound advice if you want to move this proposal forward:

> I'll just add that the way to change a proposal decision is to provide new information.  I don't see any new information here.  Continuing discussion without new information just takes time without making progress.  We have to be able to make a decision and move on, without continuously discussing the same issues.  Thanks, and thanks for taking the time to write this.

_Originally posted by @ianlancetaylor in https://github.com/golang/go/issues/46430#issuecomment-850542888_

Endlessly opening the same issue without adding information is just generating noise that diverts development time from real issues.

**Comment by dash-** [comment]
@DeanPDX I tagged you because you were in a small smattering of usernames I found quickly. I've got a bot that has many more now, so your inclusion isn't vital if you're uninterested. That having been said, you've got a perspective and you have spent the time to share it.

That having been said, I want to hear more perspectives. I'm pissed about the way the Go overlords are behaving. I am pissed about the minority party being muted. But if there is no minority party, if this isn't really an issue to people, let me know. (And no, don't just everyone chime in with how you don't think there's a problem. Let the silence speak for itself. I'll back off if I'm alone here, because I don't use Go. I'm just doing my penance for forcing other people to use it.

**Comment by kardianos** [comment]
@dash- 

I've used Go over 10 years. There will never be a ternary operator.

Also, good tech leaders don't "vote", they don't "compromise". They evaluate arguments based on reason and empirical evidence and make a decision.

You have no power in the main Go repository. Feel free to fork it here; though it would break every other tool in the ecosystem. So I wouldn't suggest it.

Also, mass notifying people like that is a good way to get on people grumpy side and possibly thing you are a troll. In open source, you get it for free, you can change it, and if you break it, you keep both parts. Have fun!

**Comment by dash-** [comment]
@kardianos Thanks for your perspective. I'm trying to stand up for the minority party here, and I've included people I think are in the minority party. I guess when people like you make it clear that you're not a part of the minority, I am legit less inclined to act this way. Am I being a troll? Maybe, if that's what it takes to stand up against a massive megacorporation. Also, tech leaders at the director level and above take the human element into consideration. There is no "reason or empirical evidence" here. There is no "right" or "wrong" regarding where that operator should be used. The only way to get that on your side is to make a different kind of argument, which I have.

**Comment by dash-** [comment]
Alright, I'll go away. I'm not sure if it's just the case that folks are afraid to stand up, or really don't care. I had the time today to make a stand for a minority, but it wouldn't even make itself heard enough for me to believe in it. I guess I should volunteer for a charity to do some work for a minority group that actually exists.

My apologies for wasting y'alls time.

**Comment by kardianos** [comment]
@dash- On a more human level, the initial creators of Go (Pike, Thompson, Griesemer) actively decided against including the ternary. This isn't some corporate decision. The rational was I believe as follows: a single ternary *can* be helpful, but it composes poorly and can create bugs. This is a similar rational for requiring blocks `{}` after "if" and "for". For instance, they have empirically seen things like `a == b? c == d?1:2 : 3 `. 

On a personal note: it is (a) unwise to frame everything in terms of power dynamics and (b) don't try to champion a cause you are not part of.

**Comment by dash-** [comment]
@kardianos You shouldn't offer me personal advice because you do not know me. I appreciate that you're trying to be helpful, but without actually knowing the person you're offering the advice to, it comes off as condescending. In this context, it also comes off as dismissive, and smells like gaslight.

Yes, it is unwise to frame everything in terms of power dynamics. If you think I do, I'm certain it would be a sampling bias on your part. I have only framed the behavior of those with power over those without power in issue 33171 in terms of power dynamics because of the significant power dynamics involved. You disagree? I protested like a member of a minority whose voice is being suppressed because I was a member of a minority whose voice is being suppressed. You don't think so? I entered the conversation March, 2020 trying to find peace between a CTO that was forcing Go on me and the people under me and a language that seemed unusable because of a few issues (including no ternary conditional operator or their various alternatives, which eventually makes code just waaaay too verbose, like this paragraph). I read everything that had been said up to that point in that issue, and commented based on what I had read. Mostly about the fact that I was seeing tons of people begging for this feature, and knew that tons of people under me wanted that feature. I also personally wanted the feature, because I too was writing some code in that position and had to use Go, and also hated these shortcomings.  

https://github.com/golang/go/issues/33171#issuecomment-596032781

The reply from Griesemer was that the conversation was already over and he wouldn't be discussing it with me. But he did defend his connection to the community. I suppose he was right, because there was no minority that I thought I was a part of. I mean there would be a minority, but they either side with him eventually, or they (like I) stop using Go.

No, I belonged in the conversation, and my experience was real and valid. I deserved to be heard. Instead, I was insulted. I also never tried to champion the cause. I was trying to instigate a champion into stepping forward. So I was playing Morpheus, not Neo.

But out of roughly 40 folks I assessed to make at least some core part of a minority group that maybe I would be a member of that could make a stand against Griesemer et al, and there's really no one, because y'all either sided with Griesemer et al or y'all stopped using Go and don't care. I know I stopped using Go.

In the end, I'm giving up yeah. There is no minority group, no one is being suppressed, because they already either gave up on the inside, or they moved on. I'm moving on. I have no love for Go or its community any further.

**Comment by dash-** [comment]
@tmthrgd Have I offended you, Tom? Say something, don't just flip me off here buddy. Using a thumbs down there is offensive to me. Is it the "I have no love" statement? Should I take that back? What have I said that bothers you? Do you think something is untrue?

**Comment by phrounz** [comment]
Honestly I have kinda given up about this issue, because generics are now accepted, and this will allow a solution at some point, which is not perfect (ifTrue and ifFalse below are both interpreted i.e. executed if they are function calls, and efficiency is questionable), but it resolves most of the issues:
```
func Ternary[T any](condition bool, ifTrue T, ifFalse T) T {
	if condition {
		return ifTrue
	}
	return ifFalse
}
fmt.Printf("Test: %s\n", Ternary[string](someEnabledFlagHere, "enabled", "not enabled"))
```

[I just played with the go2go playground](https://go2goplay.golang.org/p/9sE2aYKINzT) and generics seem to resolve some critical other issues I encoutered like the lack of functional programming style functions and Values() and Keys() methods for maps, so I am quite satisfied. Some of them [might even exist](https://github.com/golang/go/issues/45955) in the standard library, even if it seems that there is still some (IMHO irrational) resistance to any sort of functional programming by the original Go team.

I still use Golang in my daily work, and it has so many advantages (in terms of robustness particularly) compared to other languages, that I won't stop using it if I have a choice.

**Comment by dash-** [comment]
@phrounz Thank you for saying something. I feel so much more resolved about this now, and feel like everyone involved has at least had a final chance to have a say about the matter before the discussion was over. Thanks.

Should I kill this fork now, or leave it for posterity and communal closure on the issue for all to see?

**Comment by bugpowder** [comment]
Golang is not a language to depend on community involvement (except for gruntwork, like portiting to some architecture and so on). It's a top down thing. 

Swift, on the other hand, surprisingly as it comes from Apple, is more open to community proposals, participation, and so on. C# is too, but Microsoft was always more open in that.

Go is more like take it or leave it. I've seldom seen any major proposal not just being dismissed, unless it comes from the core team.
